### ISSUE TITLE
Some notes after general testing 4/20/17

### ISSUE THREAD

**Issue by rjosefsberg** [jmennick/cornDog#39] opened 2017-04-21 00:23 UTC
I know some of these are still in process, but these are just some things I noted while writing test cases. 

Bigger Stuff:
- [ ] We should probably automatically populate today's date in  a Journal Entry by default. The date input format is unclear. Also, that neat little calendar thing doesn't show up for me (Firefox).

- [ ] Should be a response if the date format is wrong (like, letters n stuff). 

- [x] You can still deactivate Accounts with pending transactions

- [x] You shouldn't be able to edit initial balance of an account once there has been posts to it. This might also count for other account attributes, we should ask.

- [x] Events aren't posting.

Little Stuff:
- [x] Add account button appears on account details page?

- [x] Add journal entry button appears in journal entry details?

- [ ] If you use the "back" button, it should always take you to the view you came from. 

- [ ] Any link to an account outside of the Manage Accounts view should probably go to the Ledger for that Account. Joe Accountant doesn't gain much from viewing the base information from an account, as he can't change it.

Like I said, just some stuff I noticed. I'll run back through on Monday to see where we stand. Thanks guys!

**Comment by gav5** [comment] 2017-04-21 15:41
@rjosefsberg The add account and add journal entry buttons in the detail pages are design choices. This is common to many business-centric data-entry applications. This is because users have to enter numerous amounts of records in great succession. If the user adds a new journal entry, they are taken to the page for that entry. If that button were not there, the user would then be required to go back to the accounts screen and then press "Add Account". This seems trivial, but the time adds up and it has a tendency to annoy the hell out of users (I have encountered this specific kind of case in my own work experience).

**Comment by gav5** [comment] 2017-04-21 15:43
@rjosefsberg "Events aren't posting." I cannot reproduce what you are talking about. Is there something specific you are doing to break this?

**Comment by rjosefsberg** [comment] 2017-04-21 15:52
The Events page is blank, despite me having made accounts/entries/postings.

**Comment by gav5** [comment] 2017-04-21 16:03
It wasn't blank. It was failing to load. This was caused by a faulty line in the seeds.rb file, which I have fixed in bfd1833ea00747136f807efb7eb081ec8072cb2c.

I had to reseed the db to fix, so your changes won't be in there anymore, but you should be able to see the events log now.

**Comment by rjosefsberg** [comment] 2017-04-21 16:08
That did it!

**Comment by gav5** [comment] 2017-04-21 18:18
"You shouldn't be able to edit initial balance of an account once there has been posts to it. This might also count for other account attributes, we should ask."

True. We shouldn't allow changes to initial balance after the account has been created. What about when the account is deactivated though? Deactivated accounts don't technically exist from the user's PoV and cannot be affected in any way.

I would think you shouldn't be able to change the "kind" of account after the fact, as it could lead to inconsistencies. If the account is inactive or could also be disabled I think this might be an okay thing to do though. Once the account is posted to is when it could cause trouble. I'm thinking something like the following computed property in [AccountForm.vue](https://github.com/jmennick/cornDog/blob/master/client/components/accounts/AccountForm.vue):
```js
canChangeKind() {
  if (this.active === false) {
    return true
  } else if (this.can_deactivate === true) {
    return true
  } else {
    return false
  }
}
```

The "name", "code", "order", and "description" fields aren't really considered in the posting process or anything like that, so they should probably be the only fields you see once the account is activated.

**Comment by gav5** [comment] 2017-04-21 18:20
"We should probably automatically populate today's date in a Journal Entry by default."

I think we asked about this and he shot it down, saying he wanted the user to explicitly state the actual date the transaction occurred on. If this were the case, lazy users might just let the date be the date they entered it even if it happened the day before. This forces them to be explicit in their entries.

**Comment by rjosefsberg** [comment] 2017-04-21 19:05
I don't remember him shooting it down persay, perhaps a formatting suggestion such "MM/DD/YYYY" should appear instead of just "Date". Also, feedback for incorrect formatting is still probably a good idea, but nonessential.

**Comment by rjosefsberg** [comment] 2017-04-21 19:06
Also, I dig your solution for the initial balance change.

**Comment by gav5** [comment] 2017-04-21 21:19
We could do the placeholder of "MM/DD/YYYY" for the case when someone actually enters this manually. The intent is to put a date picker component there instead of a HTML5 tag of type date. We just haven't gotten to it yet.

(NOTE: Google Chrome and Edge render a date picker for that; Firefox and Safari just show a normal text field).

**Closed** 2024-09-24 19:17 UTC
